[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [ValidateSet('Status', 'Stage', 'Archive', 'Restore', 'SelfTest')]
    [string]$Action,

    [Parameter(Position = 1)]
    [Alias('Variant', 'RunLabel')]
    [string]$Name,

    [string]$GameRoot = 'C:\Games\Fallout.4 1.10.163',

    # Discovery runs use diagnostics; clean timing runs should pass
    # -Diagnostics:$false to exclude diagnostic-hook/logging overhead.
    [bool]$Diagnostics = $true,

    # Loading-screen display for the staged variant. 0 (black) keeps
    # presentation cost out of the preload comparison and remains the default;
    # 3 (background + tips) measures the shipping experience instead. On OG,
    # mode 3 defers the animation-freeze speed lever until tips are captured,
    # so its timings include that real presentation cost by design.
    [ValidateRange(0, 3)]
    [int]$LoadingScreenMode = 0
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:WorkspaceRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$script:StateRoot = Join-Path $script:WorkspaceRoot 'benchmark-state'
$script:ActivePointerPath = Join-Path $script:StateRoot 'active-session.json'
$script:ExpectedRuntimeVersion = '1.10.163.0'
$script:ControlledPresentInterval = 1
$script:ControlledBorderless = 1
$script:ControlledFullScreen = 0
$script:ControlledMaximizeWindow = 0

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory = $true)][string]$LiteralPath,
        [Parameter(Mandatory = $true)][string]$Text
    )

    $parent = Split-Path -Parent $LiteralPath
    if ($parent -and -not (Test-Path -LiteralPath $parent -PathType Container)) {
        [void](New-Item -ItemType Directory -Path $parent)
    }
    [IO.File]::WriteAllText($LiteralPath, $Text, [Text.UTF8Encoding]::new($false))
}

function Set-IniValuePreservingFile {
    param(
        [Parameter(Mandatory = $true)][string]$LiteralPath,
        [Parameter(Mandatory = $true)][string]$Section,
        [Parameter(Mandatory = $true)][string]$Key,
        [Parameter(Mandatory = $true)][string]$Value
    )

    if (-not (Test-Path -LiteralPath $LiteralPath -PathType Leaf)) {
        throw "INI file does not exist: $LiteralPath"
    }

    $lines = [Collections.Generic.List[string]]::new()
    foreach ($line in [IO.File]::ReadAllLines($LiteralPath)) {
        $lines.Add($line)
    }

    $sectionHeader = '[' + $Section + ']'
    $sectionStart = -1
    $sectionEnd = $lines.Count
    for ($index = 0; $index -lt $lines.Count; $index++) {
        if ($lines[$index].Trim().Equals(
            $sectionHeader, [StringComparison]::OrdinalIgnoreCase)) {
            $sectionStart = $index
            for ($endIndex = $index + 1; $endIndex -lt $lines.Count; $endIndex++) {
                if ($lines[$endIndex].Trim() -match '^\[.+\]$') {
                    $sectionEnd = $endIndex
                    break
                }
            }
            break
        }
    }
    if ($sectionStart -lt 0) {
        throw "INI section [$Section] was not found in $LiteralPath"
    }

    $escapedKey = [Regex]::Escape($Key)
    $keyPattern = '^\s*' + $escapedKey + '\s*='
    $keyIndex = -1
    for ($index = $sectionStart + 1; $index -lt $sectionEnd; $index++) {
        if ($lines[$index] -match $keyPattern) {
            if ($keyIndex -ge 0) {
                throw "Duplicate [$Section] $Key entries in $LiteralPath"
            }
            $keyIndex = $index
        }
    }
    if ($keyIndex -ge 0) {
        $lines[$keyIndex] = "$Key=$Value"
    } else {
        $lines.Insert($sectionEnd, "$Key=$Value")
    }

    [IO.File]::WriteAllLines(
        $LiteralPath, $lines, [Text.UTF8Encoding]::new($false))
}

function New-ControlledBuffout4TomlText {
    return @"
# Generated by tools\Fallout4PreloadBenchmark.ps1 for crash-capture runs.
# Buffout's configurable fixes/patches are disabled so it does not silently
# change the Faster Loadscreens timing policy. Buffout treats any positive
# Papyrus value as permission to install its detour, so zero disables it.

[Compatibility]
F4EE = false

[Crashlog]
AutoOpen = true
PromptUpload = true
Directory = ""

[Fixes]
ActorIsHostileToActor = false
BackportedBA2Support = false
BGSAIWorldLocationRefRadiusNull = false
BSLightingShaderMaterialGlowmap = false
CellInit = false
CreateD3DAndSwapChain = false
EncounterZoneReset = false
EscapeFreeze = false
FixScriptPageAllocation = false
FixToggleScriptsCommand = false
FollowerStrayBullet = false
GreyMovies = false
InteriorNavCut = false
MagicEffectApplyEvent = false
MovementPlanner = false
PackageAllocateLocation = false
PipboyLightInvFix = false
SafeExit = false
TESObjectREFRGetEncounterZone = false
UnalignedLoad = false
UtilityShader = false
WorkBenchSwap = false

[Patches]
Achievements = false
ArchiveLimit = false
BSMTAManager = false
BSPreCulledObjects = false
BSTextureStreamerLocalHeap = false
HavokMemorySystem = false
INISettingCollection = false
InputSwitch = false
MaxStdIO = -1
MemoryManager = false
MemoryManagerDebug = false
ScaleformAllocator = false
SmallBlockAllocator = false
WorkshopMenu = false

[Tweaks]
MaxPapyrusOpsPerFrame = 0

[Warnings]
CreateTexture2D = false
ImageSpaceAdapter = false

[Debug]
WaitForDebugger = false
"@
}

function Assert-BuffoutCrashCaptureConfig {
    param([Parameter(Mandatory = $true)][string]$LiteralPath)

    if (-not (Test-Path -LiteralPath $LiteralPath -PathType Leaf)) {
        throw "Buffout4 TOML is missing: $LiteralPath"
    }
    $text = Get-Content -LiteralPath $LiteralPath -Raw
    foreach ($line in @(
        'BGSAIWorldLocationRefRadiusNull = false',
        'FixScriptPageAllocation = false',
        'FixToggleScriptsCommand = false',
        'InteriorNavCut = false',
        'WorkBenchSwap = false',
        'MemoryManager = false',
        'ScaleformAllocator = false',
        'SmallBlockAllocator = false',
        'MaxPapyrusOpsPerFrame = 0'
    )) {
        if (@($text -split '\r?\n') -notcontains $line) {
            throw "Buffout4 crash-capture config is missing '$line'"
        }
    }
}

function Write-JsonAtomic {
    param(
        [Parameter(Mandatory = $true)][string]$LiteralPath,
        [Parameter(Mandatory = $true)]$Value
    )

    $json = $Value | ConvertTo-Json -Depth 12
    $temporaryPath = "$LiteralPath.tmp"
    Write-Utf8NoBom -LiteralPath $temporaryPath -Text ($json + [Environment]::NewLine)
    Move-Item -LiteralPath $temporaryPath -Destination $LiteralPath -Force
}

function Get-Sha256 {
    param([Parameter(Mandatory = $true)][string]$LiteralPath)
    return (Get-FileHash -LiteralPath $LiteralPath -Algorithm SHA256).Hash
}

function Get-RunningGameProcesses {
    $names = @('Fallout4', 'Fallout4Launcher', 'f4se_loader', 'f4se_steam_loader')
    $found = foreach ($processName in $names) {
        Get-Process -Name $processName -ErrorAction SilentlyContinue
    }
    return @($found | Sort-Object -Property Id -Unique)
}

function Assert-GameStopped {
    $running = @(Get-RunningGameProcesses)
    if ($running.Count -gt 0) {
        $descriptions = $running | ForEach-Object { '{0} (PID {1})' -f $_.ProcessName, $_.Id }
        throw ('Fallout 4/F4SE is running: {0}. Exit it completely before this action.' -f
            ($descriptions -join ', '))
    }
}

function Get-GamePaths {
    param([Parameter(Mandatory = $true)][string]$Root)

    $documents = [Environment]::GetFolderPath('MyDocuments')
    $localAppData = [Environment]::GetFolderPath('LocalApplicationData')
    return [ordered]@{
        GameRoot       = $Root
        Runtime        = Join-Path $Root 'Fallout4.exe'
        F4SELoader     = Join-Path $Root 'f4se_loader.exe'
        F4SEPlugins    = Join-Path $Root 'Data\F4SE\Plugins'
        InstalledDll   = Join-Path $Root 'Data\F4SE\Plugins\LoadingScreens.dll'
        Buffout4Dll    = Join-Path $Root 'Data\F4SE\Plugins\Buffout4.dll'
        Buffout4Toml   = Join-Path $Root 'Data\F4SE\Plugins\Buffout4.toml'
        HighFPSPhysicsFixDll = Join-Path $Root 'Data\F4SE\Plugins\HighFPSPhysicsFix.dll'
        HighFPSPhysicsFixIni = Join-Path $Root 'Data\F4SE\Plugins\HighFPSPhysicsFix.ini'
        PackageConfig  = Join-Path $Root 'Data\MCM\Config\FasterLoadscreens\config.json'
        PackageIni     = Join-Path $Root 'Data\MCM\Config\FasterLoadscreens\settings.ini'
        UserMcmIni     = Join-Path $Root 'Data\MCM\Settings\FasterLoadscreens.ini'
        PluginsTxt     = Join-Path $localAppData 'Fallout4\plugins.txt'
        FalloutIni     = Join-Path $documents 'My Games\Fallout4\Fallout4.ini'
        FalloutPrefs   = Join-Path $documents 'My Games\Fallout4\Fallout4Prefs.ini'
        FalloutCustom  = Join-Path $documents 'My Games\Fallout4\Fallout4Custom.ini'
        F4SELogDir     = Join-Path $documents 'My Games\Fallout4\F4SE'
        LoadingLog     = Join-Path $documents 'My Games\Fallout4\F4SE\LoadingScreens.log'
        Buffout4Log    = Join-Path $documents 'My Games\Fallout4\F4SE\Buffout4.log'
    }
}

function Assert-TargetRuntime {
    param([Parameter(Mandatory = $true)]$Paths)

    if (-not (Test-Path -LiteralPath $Paths.GameRoot -PathType Container)) {
        throw "Game root does not exist: $($Paths.GameRoot)"
    }
    if (-not (Test-Path -LiteralPath $Paths.Runtime -PathType Leaf)) {
        throw "Fallout4.exe was not found: $($Paths.Runtime)"
    }
    if (-not (Test-Path -LiteralPath $Paths.F4SELoader -PathType Leaf)) {
        throw "f4se_loader.exe was not found: $($Paths.F4SELoader)"
    }

    $actualVersion = (Get-Item -LiteralPath $Paths.Runtime).VersionInfo.FileVersion
    if ($actualVersion -ne $script:ExpectedRuntimeVersion) {
        throw "Expected Fallout 4 $script:ExpectedRuntimeVersion, found $actualVersion at $($Paths.Runtime)"
    }
}

function Get-SourcePaths {
    # Multiple verification build trees may coexist. Never silently stage an
    # older build\Release DLL merely because that conventional path exists;
    # select the newest actual artifact and record its hash in the run manifest.
    $dllCandidates = @(
        (Join-Path $script:WorkspaceRoot 'build\Release\LoadingScreens.dll')
        (Join-Path $script:WorkspaceRoot 'build-verify-final\Release\LoadingScreens.dll')
        (Join-Path $script:WorkspaceRoot 'package\Data\F4SE\Plugins\LoadingScreens.dll')
    )
    $sourceDll = $dllCandidates |
        Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
        ForEach-Object { Get-Item -LiteralPath $_ } |
        Sort-Object -Property LastWriteTimeUtc -Descending |
        Select-Object -First 1 -ExpandProperty FullName

    return [ordered]@{
        Dll        = $sourceDll
        ConfigJson = Join-Path $script:WorkspaceRoot 'package\Data\MCM\Config\FasterLoadscreens\config.json'
        SettingsIni = Join-Path $script:WorkspaceRoot 'package\Data\MCM\Config\FasterLoadscreens\settings.ini'
    }
}

function Assert-SourceFiles {
    param([Parameter(Mandatory = $true)]$Sources)

    if ([string]::IsNullOrWhiteSpace([string]$Sources.Dll) -or
        -not (Test-Path -LiteralPath $Sources.Dll -PathType Leaf)) {
        throw 'No LoadingScreens.dll was found in build\Release or package\Data\F4SE\Plugins.'
    }
    foreach ($path in @($Sources.ConfigJson, $Sources.SettingsIni)) {
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
            throw "Required package file was not found: $path"
        }
    }
}

function Get-VariantProfile {
    param([Parameter(Mandatory = $true)][string]$VariantName)

    $retiredInteriorProfiles = @(
        'native-1cell',
        'native-1cell-buffer1',
        'native-1cell-buffer2',
        'crosshair',
        'plugin-native-1cell',
        'gate-native-grid',
        'candidate-minimal',
        'b-all-preload-buffer3',
        'diagnostic-gate-buffer3',
        'combined-speed-buffer3'
    )
    if ($retiredInteriorProfiles -contains $VariantName) {
        throw ("Benchmark profile '$VariantName' is retired: it selected native " +
            'linked interiors, the historical crosshair path, or the unsafe ' +
            'live-grid exterior mode. Use gate-1cell for the final safe B test.')
    }

    $profiles = @{
        'baseline' = [ordered]@{
            BenchmarkMode = 0; MenuPreload = $true; NativeLinked = $false
            PreloadExteriorGates = $false; ExteriorGateDistanceCells = 0
            InteriorCellBuffer = 3
        }
        'baseline-buffout' = [ordered]@{
            BenchmarkMode = 0; MenuPreload = $true; NativeLinked = $false
            PreloadExteriorGates = $false; ExteriorGateDistanceCells = 0
            InteriorCellBuffer = 3; Buffout4 = $true
        }
        'menu-off' = [ordered]@{
            BenchmarkMode = 0; MenuPreload = $false; NativeLinked = $false
            PreloadExteriorGates = $false; ExteriorGateDistanceCells = 0
            InteriorCellBuffer = 3
        }
        'core' = [ordered]@{
            BenchmarkMode = 1; MenuPreload = $true; NativeLinked = $false
            PreloadExteriorGates = $false; ExteriorGateDistanceCells = 0
            InteriorCellBuffer = 3
        }
        'gate-1cell' = [ordered]@{
            BenchmarkMode = 1; MenuPreload = $true; NativeLinked = $false
            PreloadExteriorGates = $true; ExteriorGateDistanceCells = 0
            InteriorCellBuffer = 3
        }
        'gate-1cell-buffout' = [ordered]@{
            BenchmarkMode = 1; MenuPreload = $true; NativeLinked = $false
            PreloadExteriorGates = $true; ExteriorGateDistanceCells = 0
            InteriorCellBuffer = 3; Buffout4 = $true
        }
        'hfpf-all-speed' = [ordered]@{
            BenchmarkMode = 0; MenuPreload = $true; NativeLinked = $false
            PreloadExteriorGates = $false; ExteriorGateDistanceCells = 0
            InteriorCellBuffer = 3; HighFPSPhysicsFix = $true
        }
    }

    if (-not $profiles.ContainsKey($VariantName)) {
        throw ('Unknown variant "{0}". Expected one of: {1}' -f
            $VariantName, (($profiles.Keys | Sort-Object) -join ', '))
    }

    $profile = $profiles[$VariantName]
    if (-not $profile.Contains('HighFPSPhysicsFix')) {
        $profile['HighFPSPhysicsFix'] = $false
    }
    if (-not $profile.Contains('Buffout4')) {
        $profile['Buffout4'] = $false
    }
    if (-not $profile.Contains('RequireDiagnostics')) {
        $profile['RequireDiagnostics'] = $false
    }
    if ([int]$profile.ExteriorGateDistanceCells -lt 0 -or
        [int]$profile.ExteriorGateDistanceCells -gt 3) {
        throw "Invalid benchmark profile '$VariantName': exterior gate distance stepper must be 0..3."
    }
    if ([int]$profile.InteriorCellBuffer -lt 1 -or
        [int]$profile.InteriorCellBuffer -gt 3) {
        throw "Invalid benchmark profile '$VariantName': interior cell buffer must be 1..3."
    }
    return $profile
}

function Get-ActiveSession {
    if (-not (Test-Path -LiteralPath $script:ActivePointerPath -PathType Leaf)) {
        return $null
    }

    $pointer = Get-Content -LiteralPath $script:ActivePointerPath -Raw | ConvertFrom-Json
    if (-not $pointer.SessionPath) {
        throw "The active-session pointer is invalid: $script:ActivePointerPath"
    }
    $sessionPath = [IO.Path]::GetFullPath([string]$pointer.SessionPath)
    $statePrefix = [IO.Path]::GetFullPath($script:StateRoot).TrimEnd('\') + '\'
    if (-not $sessionPath.StartsWith($statePrefix, [StringComparison]::OrdinalIgnoreCase)) {
        throw "The active session points outside benchmark-state: $sessionPath"
    }
    $manifestPath = Join-Path $sessionPath 'manifest.json'
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
        throw "The active benchmark manifest is missing: $manifestPath"
    }

    return [pscustomobject]@{
        SessionPath = $sessionPath
        ManifestPath = $manifestPath
        Manifest = (Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json)
    }
}

function Assert-ProfileInvocation {
    param(
        [Parameter(Mandatory = $true)][string]$VariantName,
        [Parameter(Mandatory = $true)]$Profile,
        [Parameter(Mandatory = $true)][bool]$DiagnosticsEnabled
    )
    if ([bool]$Profile.RequireDiagnostics -and -not $DiagnosticsEnabled) {
        throw "Benchmark profile '$VariantName' requires -Diagnostics:`$true."
    }
}

function Resolve-SessionRelativePath {
    param(
        [Parameter(Mandatory = $true)][string]$SessionPath,
        [Parameter(Mandatory = $true)][string]$RelativePath
    )

    $sessionFull = [IO.Path]::GetFullPath($SessionPath)
    $resolved = [IO.Path]::GetFullPath((Join-Path $sessionFull $RelativePath))
    $prefix = $sessionFull.TrimEnd('\') + '\'
    if (-not $resolved.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Manifest path escapes its session directory: $RelativePath"
    }
    return $resolved
}

function New-OriginalFileRecord {
    param(
        [Parameter(Mandatory = $true)][string]$Role,
        [Parameter(Mandatory = $true)][string]$Target,
        [Parameter(Mandatory = $true)][string]$BackupRelative
    )

    $exists = Test-Path -LiteralPath $Target -PathType Leaf
    $record = [ordered]@{
        Role = $Role
        Target = $Target
        Existed = $exists
        BackupRelative = $BackupRelative
        Sha256 = $null
        Length = $null
        LastWriteTimeUtc = $null
        Attributes = $null
    }
    if ($exists) {
        $item = Get-Item -LiteralPath $Target
        $record.Sha256 = Get-Sha256 -LiteralPath $Target
        $record.Length = $item.Length
        $record.LastWriteTimeUtc = $item.LastWriteTimeUtc.ToString('o')
        $record.Attributes = [int]$item.Attributes
    }
    return $record
}

function Backup-OriginalRecord {
    param(
        [Parameter(Mandatory = $true)][string]$SessionPath,
        [Parameter(Mandatory = $true)]$Record
    )

    if (-not $Record.Existed) {
        return
    }
    $backupPath = Resolve-SessionRelativePath -SessionPath $SessionPath -RelativePath $Record.BackupRelative
    $parent = Split-Path -Parent $backupPath
    if (-not (Test-Path -LiteralPath $parent -PathType Container)) {
        [void](New-Item -ItemType Directory -Path $parent)
    }
    Copy-Item -LiteralPath $Record.Target -Destination $backupPath
    $backupHash = Get-Sha256 -LiteralPath $backupPath
    if ($backupHash -ne $Record.Sha256) {
        throw "Backup verification failed for $($Record.Target)"
    }
}

function New-BenchmarkSession {
    param(
        [Parameter(Mandatory = $true)]$Paths
    )

    if (-not (Test-Path -LiteralPath $script:StateRoot -PathType Container)) {
        [void](New-Item -ItemType Directory -Path $script:StateRoot)
    }
    if (Test-Path -LiteralPath $script:ActivePointerPath) {
        throw "An active benchmark session already exists: $script:ActivePointerPath"
    }

    $stamp = (Get-Date).ToUniversalTime().ToString('yyyyMMdd-HHmmss-fff')
    $sessionPath = Join-Path $script:StateRoot $stamp
    [void](New-Item -ItemType Directory -Path $sessionPath)

    $records = [System.Collections.Generic.List[object]]::new()
    $trackedTargets = [System.Collections.Generic.HashSet[string]]::new(
        [StringComparer]::OrdinalIgnoreCase)

    $activeDlls = @()
    if (Test-Path -LiteralPath $Paths.F4SEPlugins -PathType Container) {
        $activeDlls = @(Get-ChildItem -LiteralPath $Paths.F4SEPlugins -File -Filter '*.dll' |
            Sort-Object -Property Name)
    }
    foreach ($dll in $activeDlls) {
        $relative = 'original\f4se-dlls\' + $dll.Name
        $records.Add((New-OriginalFileRecord -Role 'TopLevelF4SEDll' `
            -Target $dll.FullName -BackupRelative $relative))
        [void]$trackedTargets.Add($dll.FullName)
    }
    if (-not $trackedTargets.Contains($Paths.InstalledDll)) {
        $records.Add((New-OriginalFileRecord -Role 'LoadingScreensDll' `
            -Target $Paths.InstalledDll `
            -BackupRelative 'original\f4se-dlls\LoadingScreens.dll'))
        [void]$trackedTargets.Add($Paths.InstalledDll)
    }

    $managed = @(
        @('PluginList', $Paths.PluginsTxt, 'original\configuration\plugins.txt'),
        @('Fallout4Ini', $Paths.FalloutIni, 'original\configuration\Fallout4.ini'),
        @('Fallout4PrefsIni', $Paths.FalloutPrefs, 'original\configuration\Fallout4Prefs.ini'),
        @('Fallout4CustomIni', $Paths.FalloutCustom, 'original\configuration\Fallout4Custom.ini'),
        @('PackageConfig', $Paths.PackageConfig, 'original\configuration\config.json'),
        @('PackageSettings', $Paths.PackageIni, 'original\configuration\settings.ini'),
        @('UserMcmSettings', $Paths.UserMcmIni, 'original\configuration\FasterLoadscreens.ini'),
        @('Buffout4Config', $Paths.Buffout4Toml,
            'original\configuration\Buffout4.toml'),
        @('HighFPSPhysicsFixIni', $Paths.HighFPSPhysicsFixIni,
            'original\configuration\HighFPSPhysicsFix.ini')
    )
    foreach ($entry in $managed) {
        $records.Add((New-OriginalFileRecord -Role $entry[0] -Target $entry[1] `
            -BackupRelative $entry[2]))
    }

    foreach ($record in $records) {
        Backup-OriginalRecord -SessionPath $sessionPath -Record $record
    }

    $manifest = [ordered]@{
        SchemaVersion = 1
        CreatedUtc = (Get-Date).ToUniversalTime().ToString('o')
        WorkspaceRoot = $script:WorkspaceRoot
        GameRoot = $Paths.GameRoot
        RuntimeVersion = (Get-Item -LiteralPath $Paths.Runtime).VersionInfo.FileVersion
        OriginalFiles = @($records)
        CurrentVariant = $null
        CurrentDiagnostics = $null
        StageHistory = @()
        ArchiveHistory = @()
        RestoredUtc = $null
    }
    $manifestPath = Join-Path $sessionPath 'manifest.json'
    Write-JsonAtomic -LiteralPath $manifestPath -Value $manifest
    Write-JsonAtomic -LiteralPath $script:ActivePointerPath -Value ([ordered]@{
        SessionPath = $sessionPath
        CreatedUtc = $manifest.CreatedUtc
    })

    return [pscustomobject]@{
        SessionPath = $sessionPath
        ManifestPath = $manifestPath
        Manifest = (Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json)
    }
}

function Assert-SessionMatchesTarget {
    param(
        [Parameter(Mandatory = $true)]$Session,
        [Parameter(Mandatory = $true)]$Paths
    )

    if (-not ([string]$Session.Manifest.WorkspaceRoot).Equals(
        $script:WorkspaceRoot, [StringComparison]::OrdinalIgnoreCase)) {
        throw "The active session belongs to another workspace: $($Session.Manifest.WorkspaceRoot)"
    }
    if (-not ([string]$Session.Manifest.GameRoot).Equals(
        $Paths.GameRoot, [StringComparison]::OrdinalIgnoreCase)) {
        throw "The active session targets another game root: $($Session.Manifest.GameRoot)"
    }
    if ($Session.Manifest.RestoredUtc) {
        throw "The active pointer references a session already marked restored: $($Session.SessionPath)"
    }
}

function Assert-OriginalBackups {
    param([Parameter(Mandatory = $true)]$Session)

    foreach ($record in @($Session.Manifest.OriginalFiles)) {
        if (-not $record.Existed) {
            continue
        }
        $backupPath = Resolve-SessionRelativePath -SessionPath $Session.SessionPath `
            -RelativePath ([string]$record.BackupRelative)
        if (-not (Test-Path -LiteralPath $backupPath -PathType Leaf)) {
            throw "Original backup is missing: $backupPath"
        }
        if ((Get-Sha256 -LiteralPath $backupPath) -ne [string]$record.Sha256) {
            throw "Original backup hash mismatch: $backupPath"
        }
    }
}

function Disable-OriginalF4SEDlls {
    param([Parameter(Mandatory = $true)]$Session)

    foreach ($record in @($Session.Manifest.OriginalFiles |
        Where-Object { $_.Role -in @('TopLevelF4SEDll', 'LoadingScreensDll') })) {
        if (-not (Test-Path -LiteralPath $record.Target -PathType Leaf)) {
            continue
        }
        if ($record.Existed -and (Get-Sha256 -LiteralPath $record.Target) -ne [string]$record.Sha256) {
            throw "An F4SE DLL changed after it was backed up; refusing to remove it: $($record.Target)"
        }
        Remove-Item -LiteralPath $record.Target -Force
    }
}

function Get-AllowedActiveF4SEDllPaths {
    param(
        [Parameter(Mandatory = $true)]$Paths,
        [Parameter(Mandatory = $true)]$Profile
    )

    $allowed = @($Paths.InstalledDll)
    if ([bool]$Profile.Buffout4) {
        $allowed += $Paths.Buffout4Dll
    }
    if ([bool]$Profile.HighFPSPhysicsFix) {
        $allowed += $Paths.HighFPSPhysicsFixDll
    }
    return $allowed
}

function Disable-UnselectedOriginalF4SEDlls {
    param(
        [Parameter(Mandatory = $true)]$Session,
        [Parameter(Mandatory = $true)][string[]]$AllowedDllPaths
    )

    $allowed = [System.Collections.Generic.HashSet[string]]::new(
        [StringComparer]::OrdinalIgnoreCase)
    foreach ($path in $AllowedDllPaths) {
        [void]$allowed.Add([IO.Path]::GetFullPath($path))
    }

    foreach ($record in @($Session.Manifest.OriginalFiles |
        Where-Object { $_.Role -in @('TopLevelF4SEDll', 'LoadingScreensDll') })) {
        $target = [IO.Path]::GetFullPath([string]$record.Target)
        if ($allowed.Contains($target) -or
            -not (Test-Path -LiteralPath $target -PathType Leaf)) {
            continue
        }
        if ($record.Existed -and
            (Get-Sha256 -LiteralPath $target) -ne [string]$record.Sha256) {
            throw ("An unselected F4SE DLL changed after it was backed up; " +
                "refusing to remove it: $target")
        }
        Remove-Item -LiteralPath $target -Force
    }
}

function Assert-HighFPSPhysicsFixSpeedConfig {
    param([Parameter(Mandatory = $true)][string]$LiteralPath)

    if (-not (Test-Path -LiteralPath $LiteralPath -PathType Leaf)) {
        throw "High FPS Physics Fix INI is missing: $LiteralPath"
    }
    $text = Get-Content -LiteralPath $LiteralPath -Raw
    $requirements = [ordered]@{
        UntieSpeedFromFPS = 'true'
        DisableiFPSClamp = 'true'
        EnableVSync = 'true'
        VSyncPresentInterval = '1'
        AllowTearing = 'true'
        DisableVSyncWhileLoading = 'true'
        DisableBlackLoadingScreens = 'true'
        DisableAnimationOnLoadingScreens = 'true'
        PostloadingMenuSpeed = '2(?:\.0+)?'
        InGameFPS = '0(?:\.0+)?'
        ExteriorFPS = '0(?:\.0+)?'
        InteriorFPS = '0(?:\.0+)?'
        LoadingScreenFPS = '350(?:\.0+)?'
        OneThreadWhileLoading = 'false'
        FramerateLimitMode = '0'
        FixCPUThreads = 'true'
        FixLoadingModel = 'true'
        EnableOSD = 'false'
        LoadingTime = 'false'
        Bare_LoadingTime = 'false'
    }
    foreach ($setting in $requirements.GetEnumerator()) {
        $pattern = '(?im)^\s*' + [Regex]::Escape([string]$setting.Key) +
            '\s*=\s*' + [string]$setting.Value + '\s*(?:[#;].*)?$'
        if ($text -notmatch $pattern) {
            throw ("High FPS Physics Fix speed setting is not in the controlled " +
                "state: {0}" -f $setting.Key)
        }
    }
}

function Set-HighFPSPhysicsFixSpeedConfig {
    param([Parameter(Mandatory = $true)][string]$LiteralPath)

    $values = @(
        @('Main', 'UntieSpeedFromFPS', 'true'),
        @('Main', 'DisableiFPSClamp', 'true'),
        @('Main', 'EnableVSync', 'true'),
        @('Main', 'VSyncPresentInterval', '1'),
        @('Main', 'AllowTearing', 'true'),
        @('Main', 'DisableVSyncWhileLoading', 'true'),
        @('Main', 'DisableBlackLoadingScreens', 'true'),
        @('Main', 'DisableAnimationOnLoadingScreens', 'true'),
        @('Main', 'PostloadingMenuSpeed', '2.0'),
        @('Limiter', 'InGameFPS', '0.0'),
        @('Limiter', 'ExteriorFPS', '0.0'),
        @('Limiter', 'InteriorFPS', '0.0'),
        @('Limiter', 'LoadingScreenFPS', '350.0'),
        @('Limiter', 'OneThreadWhileLoading', 'false'),
        @('Limiter', 'FramerateLimitMode', '0'),
        @('Fixes', 'FixCPUThreads', 'true'),
        @('Fixes', 'FixLoadingModel', 'true'),
        @('OSD', 'EnableOSD', 'false'),
        @('OSD', 'LoadingTime', 'false'),
        @('OSD', 'Bare_LoadingTime', 'false')
    )
    foreach ($entry in $values) {
        Set-IniValuePreservingFile -LiteralPath $LiteralPath `
            -Section $entry[0] -Key $entry[1] -Value $entry[2]
    }
}

function Assert-NoUnexpectedActiveDlls {
    param(
        [Parameter(Mandatory = $true)]$Paths,
        [Parameter(Mandatory = $true)]$Session,
        [Parameter(Mandatory = $true)][string[]]$AllowedDllPaths
    )

    if (-not (Test-Path -LiteralPath $Paths.F4SEPlugins -PathType Container)) {
        return
    }
    $allowed = [System.Collections.Generic.HashSet[string]]::new(
        [StringComparer]::OrdinalIgnoreCase)
    foreach ($path in $AllowedDllPaths) {
        [void]$allowed.Add([IO.Path]::GetFullPath($path))
    }
    $active = @(Get-ChildItem -LiteralPath $Paths.F4SEPlugins -File -Filter '*.dll')
    $unexpected = @($active | Where-Object {
        -not $allowed.Contains($_.FullName)
    })
    if ($unexpected.Count -gt 0) {
        throw ('Unexpected F4SE DLL(s) appeared during the benchmark session: {0}. ' +
            'Move them out or run Restore before continuing.' -f
            (($unexpected | ForEach-Object Name) -join ', '))
    }
}

function Get-BooleanIniValue {
    param([Parameter(Mandatory = $true)][bool]$Value)
    if ($Value) { return '1' }
    return '0'
}

function New-UserMcmText {
    param(
        [Parameter(Mandatory = $true)][string]$VariantName,
        [Parameter(Mandatory = $true)]$Profile,
        [Parameter(Mandatory = $true)][string]$SessionPath,
        [Parameter(Mandatory = $true)][bool]$DiagnosticsEnabled,
        [Parameter(Mandatory = $true)][int]$LoadingScreenModeValue
    )

    $exteriorGate = Get-BooleanIniValue -Value ([bool]$Profile.PreloadExteriorGates)
    $diagnosticsValue = Get-BooleanIniValue -Value $DiagnosticsEnabled
    $created = (Get-Date).ToUniversalTime().ToString('o')
    return @"
; Generated by tools\Fallout4PreloadBenchmark.ps1
; Variant=$VariantName
; Session=$SessionPath
; StagedUtc=$created

[Main]
iLoadingScreenMode=$LoadingScreenModeValue
iBenchmarkMode=$($Profile.BenchmarkMode)
bVanillaFades=1
fMinSecondsForLoadFadeIn=1.5
fLoadGameFadeSecs=1.0
fFadeToBlackFadeSeconds=1.0
fAutoDoorFadeSecs=0.5
fNormalDoorFadeSecs=0.4
fNormalDoorFadeWait=0.01

[DoorPrefetch]
bPreloadExteriorGates=$exteriorGate
iExteriorGateDistanceCells=$($Profile.ExteriorGateDistanceCells)

[Diagnostics]
bPreloadDiagnostics=$diagnosticsValue
"@
}

function New-ControlledCustomIniText {
    param(
        [Parameter(Mandatory = $true)][string]$VariantName,
        [Parameter(Mandatory = $true)]$Profile
    )

    $menu = Get-BooleanIniValue -Value ([bool]$Profile.MenuPreload)
    $native = Get-BooleanIniValue -Value ([bool]$Profile.NativeLinked)
    return @"
; Generated for Fallout 4 preload benchmark variant: $VariantName
; Original file is preserved in the active benchmark session.

[General]
bUseMenuLoadCellPreload=$menu
bPreloadLinkedAreas=$native
fTeleportPreloadDistance=2048.0000
uGridsToLoad=5
uInterior Cell Buffer=$($Profile.InteriorCellBuffer)

[Archive]
bInvalidateOlderFiles=0
sResourceDataDirsFinal=STRINGS\
"@
}

function Install-Variant {
    param(
        [Parameter(Mandatory = $true)][string]$VariantName,
        [Parameter(Mandatory = $true)]$Profile,
        [Parameter(Mandatory = $true)]$Paths,
        [Parameter(Mandatory = $true)]$Sources,
        [Parameter(Mandatory = $true)]$Session,
        [Parameter(Mandatory = $true)][bool]$DiagnosticsEnabled,
        [Parameter(Mandatory = $true)][int]$LoadingScreenModeValue
    )

    Assert-OriginalBackups -Session $Session
    $allowedDllPaths = Get-AllowedActiveF4SEDllPaths -Paths $Paths -Profile $Profile
    Assert-NoUnexpectedActiveDlls -Paths $Paths -Session $Session `
        -AllowedDllPaths $allowedDllPaths

    foreach ($directory in @(
        $Paths.F4SEPlugins,
        (Split-Path -Parent $Paths.PackageConfig),
        (Split-Path -Parent $Paths.UserMcmIni),
        (Split-Path -Parent $Paths.PluginsTxt),
        (Split-Path -Parent $Paths.FalloutCustom)
    )) {
        if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
            [void](New-Item -ItemType Directory -Path $directory)
        }
    }

    Copy-Item -LiteralPath $Sources.Dll -Destination $Paths.InstalledDll -Force
    $buffout4Hash = $null
    if ([bool]$Profile.Buffout4) {
        $buffoutRecords = @($Session.Manifest.OriginalFiles | Where-Object {
            $_.Role -eq 'TopLevelF4SEDll' -and
            ([IO.Path]::GetFileName([string]$_.Target)).Equals(
                'Buffout4.dll', [StringComparison]::OrdinalIgnoreCase)
        })
        if ($buffoutRecords.Count -ne 1 -or -not $buffoutRecords[0].Existed) {
            throw 'The benchmark session has no verified original Buffout4.dll backup.'
        }
        $buffoutBackup = Resolve-SessionRelativePath `
            -SessionPath $Session.SessionPath `
            -RelativePath ([string]$buffoutRecords[0].BackupRelative)
        Copy-Item -LiteralPath $buffoutBackup `
            -Destination $Paths.Buffout4Dll -Force
        $buffout4Hash = Get-Sha256 -LiteralPath $Paths.Buffout4Dll
        if ($buffout4Hash -ne [string]$buffoutRecords[0].Sha256) {
            throw 'Installed Buffout4.dll does not match its verified session backup.'
        }
        Write-Utf8NoBom -LiteralPath $Paths.Buffout4Toml `
            -Text (New-ControlledBuffout4TomlText)
        Assert-BuffoutCrashCaptureConfig -LiteralPath $Paths.Buffout4Toml
    }
    $highFPSPhysicsFixHash = $null
    if ([bool]$Profile.HighFPSPhysicsFix) {
        $highFPSRecords = @($Session.Manifest.OriginalFiles | Where-Object {
            $_.Role -eq 'TopLevelF4SEDll' -and
            ([IO.Path]::GetFileName([string]$_.Target)).Equals(
                'HighFPSPhysicsFix.dll', [StringComparison]::OrdinalIgnoreCase)
        })
        if ($highFPSRecords.Count -ne 1 -or -not $highFPSRecords[0].Existed) {
            throw 'The benchmark session has no verified original HighFPSPhysicsFix.dll backup.'
        }
        $highFPSIniRecords = @($Session.Manifest.OriginalFiles | Where-Object {
            $_.Role -eq 'HighFPSPhysicsFixIni'
        })
        if ($highFPSIniRecords.Count -ne 1 -or
            -not $highFPSIniRecords[0].Existed) {
            throw ('The benchmark session has no verified original ' +
                'HighFPSPhysicsFix.ini backup. Restore and start a new session.')
        }
        $highFPSBackup = Resolve-SessionRelativePath `
            -SessionPath $Session.SessionPath `
            -RelativePath ([string]$highFPSRecords[0].BackupRelative)
        Copy-Item -LiteralPath $highFPSBackup `
            -Destination $Paths.HighFPSPhysicsFixDll -Force
        $highFPSPhysicsFixHash = Get-Sha256 -LiteralPath $Paths.HighFPSPhysicsFixDll
        if ($highFPSPhysicsFixHash -ne [string]$highFPSRecords[0].Sha256) {
            throw 'Installed HighFPSPhysicsFix.dll does not match its verified session backup.'
        }
        Set-HighFPSPhysicsFixSpeedConfig `
            -LiteralPath $Paths.HighFPSPhysicsFixIni
        Assert-HighFPSPhysicsFixSpeedConfig `
            -LiteralPath $Paths.HighFPSPhysicsFixIni
    }
    Copy-Item -LiteralPath $Sources.ConfigJson -Destination $Paths.PackageConfig -Force
    Copy-Item -LiteralPath $Sources.SettingsIni -Destination $Paths.PackageIni -Force

    Write-Utf8NoBom -LiteralPath $Paths.UserMcmIni `
        -Text (New-UserMcmText -VariantName $VariantName -Profile $Profile `
            -SessionPath $Session.SessionPath -DiagnosticsEnabled $DiagnosticsEnabled `
            -LoadingScreenModeValue $LoadingScreenModeValue)
    Write-Utf8NoBom -LiteralPath $Paths.FalloutCustom `
        -Text (New-ControlledCustomIniText -VariantName $VariantName -Profile $Profile)
    $presentIntervalValue = [string]$script:ControlledPresentInterval
    Set-IniValuePreservingFile -LiteralPath $Paths.FalloutIni `
        -Section 'Display' -Key 'iPresentInterval' -Value $presentIntervalValue
    Set-IniValuePreservingFile -LiteralPath $Paths.FalloutPrefs `
        -Section 'Display' -Key 'iPresentInterval' -Value $presentIntervalValue
    Set-IniValuePreservingFile -LiteralPath $Paths.FalloutPrefs `
        -Section 'Display' -Key 'bBorderless' `
        -Value ([string]$script:ControlledBorderless)
    Set-IniValuePreservingFile -LiteralPath $Paths.FalloutPrefs `
        -Section 'Display' -Key 'bFull Screen' `
        -Value ([string]$script:ControlledFullScreen)
    Set-IniValuePreservingFile -LiteralPath $Paths.FalloutPrefs `
        -Section 'Display' -Key 'bMaximizeWindow' `
        -Value ([string]$script:ControlledMaximizeWindow)
    Write-Utf8NoBom -LiteralPath $Paths.PluginsTxt -Text @"
# Generated for the Faster Loadscreens controlled benchmark.
# All non-default ESP/ESL plugins are intentionally disabled.
"@

    $remainingDlls = @(Get-ChildItem -LiteralPath $Paths.F4SEPlugins -File -Filter '*.dll')
    $allowedDllSet = [System.Collections.Generic.HashSet[string]]::new(
        [StringComparer]::OrdinalIgnoreCase)
    foreach ($path in $allowedDllPaths) {
        [void]$allowedDllSet.Add([IO.Path]::GetFullPath($path))
    }
    $unexpectedDlls = @($remainingDlls | Where-Object {
        -not $allowedDllSet.Contains($_.FullName)
    })
    if ($remainingDlls.Count -ne $allowedDllSet.Count -or
        $unexpectedDlls.Count -gt 0) {
        throw ('Isolation verification failed: active top-level F4SE DLLs do not ' +
            'match the selected profile.')
    }

    $installedHash = Get-Sha256 -LiteralPath $Paths.InstalledDll
    $sourceHash = Get-Sha256 -LiteralPath $Sources.Dll
    if ($installedHash -ne $sourceHash) {
        throw 'Installed LoadingScreens.dll does not match the selected workspace DLL.'
    }

    $entry = [ordered]@{
        Variant = $VariantName
        StagedUtc = (Get-Date).ToUniversalTime().ToString('o')
        BenchmarkMode = [int]$Profile.BenchmarkMode
        LoadingScreenMode = $LoadingScreenModeValue
        MenuPreload = [bool]$Profile.MenuPreload
        NativeLinked = [bool]$Profile.NativeLinked
        InteriorCellBuffer = [int]$Profile.InteriorCellBuffer
        PresentInterval = $script:ControlledPresentInterval
        DisplayMode = 'borderless-windowed'
        Borderless = $script:ControlledBorderless
        FullScreen = $script:ControlledFullScreen
        MaximizeWindow = $script:ControlledMaximizeWindow
        HighFPSPhysicsFix = [bool]$Profile.HighFPSPhysicsFix
        HighFPSPhysicsFixSha256 = $highFPSPhysicsFixHash
        Buffout4 = [bool]$Profile.Buffout4
        Buffout4Sha256 = $buffout4Hash
        Buffout4ConfigSha256 = if ([bool]$Profile.Buffout4) {
            Get-Sha256 -LiteralPath $Paths.Buffout4Toml
        } else {
            $null
        }
        ExteriorGate = [bool]$Profile.PreloadExteriorGates
        ExteriorGateDistanceStepper = [int]$Profile.ExteriorGateDistanceCells
        ExteriorGateDistanceCells = [int]$Profile.ExteriorGateDistanceCells + 1
        ExteriorPreloadMode = 'engine-single-cell'
        Diagnostics = $DiagnosticsEnabled
        SourceDll = $Sources.Dll
        SourceDllSha256 = $sourceHash
    }
    $Session.Manifest.CurrentVariant = $VariantName
    $Session.Manifest.CurrentDiagnostics = $DiagnosticsEnabled
    $Session.Manifest.StageHistory = @($Session.Manifest.StageHistory) + @($entry)
    Write-JsonAtomic -LiteralPath $Session.ManifestPath -Value $Session.Manifest
    $Session.Manifest = Get-Content -LiteralPath $Session.ManifestPath -Raw | ConvertFrom-Json

    return $entry
}

function Invoke-Stage {
    param(
        [Parameter(Mandatory = $true)][string]$VariantName,
        [Parameter(Mandatory = $true)]$Paths,
        [Parameter(Mandatory = $true)][bool]$DiagnosticsEnabled,
        [Parameter(Mandatory = $true)][int]$LoadingScreenModeValue
    )

    Assert-GameStopped
    Assert-TargetRuntime -Paths $Paths
    $sources = Get-SourcePaths
    Assert-SourceFiles -Sources $sources
    $profile = Get-VariantProfile -VariantName $VariantName
    Assert-ProfileInvocation -VariantName $VariantName -Profile $profile `
        -DiagnosticsEnabled $DiagnosticsEnabled
    $allowedDllPaths = Get-AllowedActiveF4SEDllPaths `
        -Paths $Paths -Profile $profile

    $session = Get-ActiveSession
    $newSession = $false
    if ($null -eq $session) {
        $session = New-BenchmarkSession -Paths $Paths
        $newSession = $true
    } else {
        Assert-SessionMatchesTarget -Session $session -Paths $Paths
    }

    try {
        if ($newSession) {
            Disable-OriginalF4SEDlls -Session $session
        } else {
            Disable-UnselectedOriginalF4SEDlls -Session $session `
                -AllowedDllPaths $allowedDllPaths
            Assert-NoUnexpectedActiveDlls -Paths $Paths -Session $session `
                -AllowedDllPaths $allowedDllPaths
        }
        $entry = Install-Variant -VariantName $VariantName -Profile $profile `
            -Paths $Paths -Sources $sources -Session $session `
            -DiagnosticsEnabled $DiagnosticsEnabled `
            -LoadingScreenModeValue $LoadingScreenModeValue
    } catch {
        throw ("Stage failed. The original files are preserved in {0}; run Restore after " +
            "resolving the reported problem.`n{1}" -f $session.SessionPath, $_.Exception.Message)
    }

    Write-Host "Staged '$VariantName' for Fallout 4 $script:ExpectedRuntimeVersion."
    Write-Host "Session: $($session.SessionPath)"
    Write-Host "LoadingScreens.dll SHA-256: $($entry.SourceDllSha256)"
    Write-Host (('Controls: benchmark={0}, loadscreen-mode={1}, menu={2}, ' +
        'native-linked={3}, interior-buffer={4}, exterior-gate={5}, ' +
        'gate-distance={6} cell(s), exterior-preload={7}, diagnostics={8}, ' +
        'hfpf={9}, buffout={10}') -f
        $entry.BenchmarkMode, $entry.LoadingScreenMode, $entry.MenuPreload,
        $entry.NativeLinked, $entry.InteriorCellBuffer,
        $entry.ExteriorGate, $entry.ExteriorGateDistanceCells,
        $entry.ExteriorPreloadMode, $entry.Diagnostics,
        $entry.HighFPSPhysicsFix, $entry.Buffout4)
    Write-Host 'Unselected top-level F4SE DLLs, active plugins, and loose-file invalidation are disabled.'
    Write-Host 'Launch with f4se_loader.exe; fully exit the game before Archive or another Stage.'
}

function Copy-ArchiveFile {
    param(
        [Parameter(Mandatory = $true)][string]$Source,
        [Parameter(Mandatory = $true)][string]$Destination,
        [Parameter(Mandatory = $true)]
        [AllowEmptyCollection()]
        [System.Collections.Generic.List[object]]$Records
    )

    if (-not (Test-Path -LiteralPath $Source -PathType Leaf)) {
        return
    }
    $parent = Split-Path -Parent $Destination
    if (-not (Test-Path -LiteralPath $parent -PathType Container)) {
        [void](New-Item -ItemType Directory -Path $parent)
    }
    Copy-Item -LiteralPath $Source -Destination $Destination
    $Records.Add([ordered]@{
        Source = $Source
        ArchivedAs = $Destination
        Sha256 = Get-Sha256 -LiteralPath $Destination
        Length = (Get-Item -LiteralPath $Destination).Length
        LastWriteTimeUtc = (Get-Item -LiteralPath $Source).LastWriteTimeUtc.ToString('o')
    })
}

function Invoke-Archive {
    param(
        [Parameter(Mandatory = $true)][string]$RunLabel,
        [Parameter(Mandatory = $true)]$Paths
    )

    Assert-GameStopped
    if ($RunLabel -notmatch '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$') {
        throw 'Run label must be 1-64 characters using letters, numbers, dot, underscore, or hyphen.'
    }
    $session = Get-ActiveSession
    if ($null -eq $session) {
        throw 'There is no active benchmark session to archive.'
    }
    Assert-SessionMatchesTarget -Session $session -Paths $Paths

    $stamp = (Get-Date).ToUniversalTime().ToString('yyyyMMdd-HHmmss-fff')
    $runPath = Join-Path $session.SessionPath ('runs\' + $stamp + '-' + $RunLabel)
    [void](New-Item -ItemType Directory -Path $runPath)
    $records = [System.Collections.Generic.List[object]]::new()

    $logCandidates = @(
        (Join-Path $Paths.F4SELogDir 'LoadingScreens.log'),
        (Join-Path $Paths.F4SELogDir 'LoadingScreens.prev.log'),
        (Join-Path $Paths.F4SELogDir 'f4se.log'),
        (Join-Path $Paths.F4SELogDir 'f4se_loader.log')
    )
    $currentStage = @($session.Manifest.StageHistory) | Select-Object -Last 1
    $buffoutActive = $null -ne $currentStage -and
        $currentStage.PSObject.Properties.Name -contains 'Buffout4' -and
        [bool]$currentStage.Buffout4
    if ($buffoutActive) {
        $logCandidates += $Paths.Buffout4Log
        $stagedUtc = [DateTime]::Parse(
            [string]$currentStage.StagedUtc,
            [Globalization.CultureInfo]::InvariantCulture,
            [Globalization.DateTimeStyles]::RoundtripKind).ToUniversalTime()
        $logCandidates += @(Get-ChildItem -LiteralPath $Paths.F4SELogDir `
            -File -Filter 'crash-*.log' -ErrorAction SilentlyContinue | Where-Object {
                $_.LastWriteTimeUtc -ge $stagedUtc
            } | Select-Object -ExpandProperty FullName)
    }
    foreach ($logPath in $logCandidates) {
        Copy-ArchiveFile -Source $logPath `
            -Destination (Join-Path $runPath ('logs\' + (Split-Path -Leaf $logPath))) `
            -Records $records
    }

    $configuration = @(
        [pscustomobject]@{
            Source = $Paths.UserMcmIni
            Relative = 'configuration\FasterLoadscreens.ini'
        }
        [pscustomobject]@{
            Source = $Paths.PackageIni
            Relative = 'configuration\settings.ini'
        }
        [pscustomobject]@{
            Source = $Paths.PackageConfig
            Relative = 'configuration\config.json'
        }
        [pscustomobject]@{
            Source = $Paths.FalloutCustom
            Relative = 'configuration\Fallout4Custom.ini'
        }
        [pscustomobject]@{
            Source = $Paths.FalloutIni
            Relative = 'configuration\Fallout4.ini'
        }
        [pscustomobject]@{
            Source = $Paths.FalloutPrefs
            Relative = 'configuration\Fallout4Prefs.ini'
        }
        [pscustomobject]@{
            Source = $Paths.HighFPSPhysicsFixIni
            Relative = 'configuration\HighFPSPhysicsFix.ini'
        }
        [pscustomobject]@{
            Source = $Paths.PluginsTxt
            Relative = 'configuration\plugins.txt'
        }
        [pscustomobject]@{
            Source = $Paths.InstalledDll
            Relative = 'plugin\LoadingScreens.dll'
        }
    )
    if (Test-Path -LiteralPath $Paths.HighFPSPhysicsFixDll -PathType Leaf) {
        $configuration += [pscustomobject]@{
            Source = $Paths.HighFPSPhysicsFixDll
            Relative = 'plugin\HighFPSPhysicsFix.dll'
        }
    }
    if ($buffoutActive) {
        $configuration += [pscustomobject]@{
            Source = $Paths.Buffout4Dll
            Relative = 'plugin\Buffout4.dll'
        }
        $configuration += [pscustomobject]@{
            Source = $Paths.Buffout4Toml
            Relative = 'configuration\Buffout4.toml'
        }
    }
    foreach ($item in $configuration) {
        Copy-ArchiveFile -Source $item.Source `
            -Destination (Join-Path $runPath $item.Relative) `
            -Records $records
    }

    # Hash the runtime/toolchain in place instead of copying Fallout4.exe into
    # every repeat archive.
    $evidence = [System.Collections.Generic.List[object]]::new()
    foreach ($evidencePath in @(
        $Paths.Runtime,
        $Paths.F4SELoader,
        $Paths.InstalledDll,
        $Paths.Buffout4Dll,
        $Paths.HighFPSPhysicsFixDll
    )) {
        if (-not (Test-Path -LiteralPath $evidencePath -PathType Leaf)) {
            continue
        }
        $item = Get-Item -LiteralPath $evidencePath
        $evidence.Add([ordered]@{
            Path = $evidencePath
            Sha256 = Get-Sha256 -LiteralPath $evidencePath
            Length = $item.Length
            LastWriteTimeUtc = $item.LastWriteTimeUtc.ToString('o')
            FileVersion = $item.VersionInfo.FileVersion
        })
    }

    $runMetadata = [ordered]@{
        SchemaVersion = 1
        Label = $RunLabel
        Variant = $session.Manifest.CurrentVariant
        Diagnostics = $session.Manifest.CurrentDiagnostics
        ArchivedUtc = (Get-Date).ToUniversalTime().ToString('o')
        SessionPath = $session.SessionPath
        GameRoot = $Paths.GameRoot
        RuntimeVersion = (Get-Item -LiteralPath $Paths.Runtime).VersionInfo.FileVersion
        Files = @($records)
        Evidence = @($evidence)
    }
    Write-JsonAtomic -LiteralPath (Join-Path $runPath 'run.json') -Value $runMetadata

    $archiveEntry = [ordered]@{
        Label = $RunLabel
        Variant = $session.Manifest.CurrentVariant
        Diagnostics = $session.Manifest.CurrentDiagnostics
        ArchivedUtc = $runMetadata.ArchivedUtc
        RunPath = $runPath
        FileCount = $records.Count
    }
    $session.Manifest.ArchiveHistory = @($session.Manifest.ArchiveHistory) + @($archiveEntry)
    Write-JsonAtomic -LiteralPath $session.ManifestPath -Value $session.Manifest

    Write-Host "Archived '$RunLabel' ($($session.Manifest.CurrentVariant)) to:"
    Write-Host $runPath
    if (-not (Test-Path -LiteralPath $Paths.LoadingLog -PathType Leaf)) {
        Write-Warning 'LoadingScreens.log was not present; the archive still contains the staged configuration and hashes.'
    }
}

function Save-PreRestoreFiles {
    param(
        [Parameter(Mandatory = $true)]$Paths,
        [Parameter(Mandatory = $true)]$Session
    )

    $stamp = (Get-Date).ToUniversalTime().ToString('yyyyMMdd-HHmmss-fff')
    $saveRoot = Join-Path $Session.SessionPath ('pre-restore\' + $stamp)
    $targets = [System.Collections.Generic.List[string]]::new()
    foreach ($record in @($Session.Manifest.OriginalFiles)) {
        if (Test-Path -LiteralPath $record.Target -PathType Leaf) {
            $targets.Add([string]$record.Target)
        }
    }
    if (Test-Path -LiteralPath $Paths.F4SEPlugins -PathType Container) {
        foreach ($dll in @(Get-ChildItem -LiteralPath $Paths.F4SEPlugins -File -Filter '*.dll')) {
            if (-not $targets.Contains($dll.FullName)) {
                $targets.Add($dll.FullName)
            }
        }
    }

    $index = 0
    foreach ($target in $targets) {
        $leaf = Split-Path -Leaf $target
        $destination = Join-Path $saveRoot ('{0:D3}-{1}' -f $index, $leaf)
        $parent = Split-Path -Parent $destination
        if (-not (Test-Path -LiteralPath $parent -PathType Container)) {
            [void](New-Item -ItemType Directory -Path $parent)
        }
        Copy-Item -LiteralPath $target -Destination $destination
        $index++
    }
    return $saveRoot
}

function Restore-OriginalRecord {
    param(
        [Parameter(Mandatory = $true)][string]$SessionPath,
        [Parameter(Mandatory = $true)]$Record
    )

    if ($Record.Existed) {
        $backupPath = Resolve-SessionRelativePath -SessionPath $SessionPath `
            -RelativePath ([string]$Record.BackupRelative)
        if (-not (Test-Path -LiteralPath $backupPath -PathType Leaf)) {
            throw "Cannot restore missing backup: $backupPath"
        }
        if ((Get-Sha256 -LiteralPath $backupPath) -ne [string]$Record.Sha256) {
            throw "Cannot restore corrupted backup: $backupPath"
        }
        $parent = Split-Path -Parent ([string]$Record.Target)
        if (-not (Test-Path -LiteralPath $parent -PathType Container)) {
            [void](New-Item -ItemType Directory -Path $parent)
        }
        Copy-Item -LiteralPath $backupPath -Destination $Record.Target -Force
        $restored = Get-Item -LiteralPath $Record.Target
        if ($Record.LastWriteTimeUtc -is [DateTime]) {
            $restored.LastWriteTimeUtc =
                ([DateTime]$Record.LastWriteTimeUtc).ToUniversalTime()
        } else {
            $restored.LastWriteTimeUtc = [DateTime]::Parse(
                [string]$Record.LastWriteTimeUtc,
                [Globalization.CultureInfo]::InvariantCulture,
                [Globalization.DateTimeStyles]::RoundtripKind)
        }
        $restored.Attributes = [IO.FileAttributes]([int]$Record.Attributes)
        if ((Get-Sha256 -LiteralPath $Record.Target) -ne [string]$Record.Sha256) {
            throw "Restored file verification failed: $($Record.Target)"
        }
    } elseif (Test-Path -LiteralPath $Record.Target -PathType Leaf) {
        Remove-Item -LiteralPath $Record.Target -Force
    }
}

function Invoke-Restore {
    param([Parameter(Mandatory = $true)]$Paths)

    Assert-GameStopped
    $session = Get-ActiveSession
    if ($null -eq $session) {
        Write-Host 'No active benchmark session; nothing to restore.'
        return
    }
    Assert-SessionMatchesTarget -Session $session -Paths $Paths
    Assert-OriginalBackups -Session $session

    $preRestorePath = Save-PreRestoreFiles -Paths $Paths -Session $session

    $originalDllTargets = [System.Collections.Generic.HashSet[string]]::new(
        [StringComparer]::OrdinalIgnoreCase)
    foreach ($record in @($session.Manifest.OriginalFiles |
        Where-Object { $_.Role -in @('TopLevelF4SEDll', 'LoadingScreensDll') })) {
        [void]$originalDllTargets.Add([string]$record.Target)
    }
    if (Test-Path -LiteralPath $Paths.F4SEPlugins -PathType Container) {
        foreach ($dll in @(Get-ChildItem -LiteralPath $Paths.F4SEPlugins -File -Filter '*.dll')) {
            if (-not $originalDllTargets.Contains($dll.FullName)) {
                Remove-Item -LiteralPath $dll.FullName -Force
            }
        }
    }

    foreach ($record in @($session.Manifest.OriginalFiles)) {
        Restore-OriginalRecord -SessionPath $session.SessionPath -Record $record
    }

    $session.Manifest.RestoredUtc = (Get-Date).ToUniversalTime().ToString('o')
    Write-JsonAtomic -LiteralPath $session.ManifestPath -Value $session.Manifest
    Remove-Item -LiteralPath $script:ActivePointerPath -Force

    Write-Host 'Restored every file captured at the start of the benchmark session.'
    Write-Host "Session retained at: $($session.SessionPath)"
    Write-Host "The final staged state was preserved at: $preRestorePath"
}

function Get-ActivePluginNames {
    param([Parameter(Mandatory = $true)][string]$PluginsPath)
    if (-not (Test-Path -LiteralPath $PluginsPath -PathType Leaf)) {
        return @()
    }
    return @(Get-Content -LiteralPath $PluginsPath | Where-Object {
        $_ -match '^\s*\*'
    } | ForEach-Object {
        ($_ -replace '^\s*\*', '').Trim()
    })
}

function Invoke-Status {
    param([Parameter(Mandatory = $true)]$Paths)

    Write-Host "Workspace: $script:WorkspaceRoot"
    Write-Host "Game root: $($Paths.GameRoot)"
    if (Test-Path -LiteralPath $Paths.Runtime -PathType Leaf) {
        Write-Host "Runtime: $((Get-Item -LiteralPath $Paths.Runtime).VersionInfo.FileVersion)"
    } else {
        Write-Host 'Runtime: missing'
    }

    $running = @(Get-RunningGameProcesses)
    if ($running.Count -eq 0) {
        Write-Host 'Game process: stopped'
    } else {
        Write-Host ('Game process: {0}' -f (($running | ForEach-Object {
            '{0}({1})' -f $_.ProcessName, $_.Id
        }) -join ', '))
    }

    $session = Get-ActiveSession
    if ($null -eq $session) {
        Write-Host 'Benchmark session: none'
    } else {
        Write-Host "Benchmark session: $($session.SessionPath)"
        Write-Host "Current variant: $($session.Manifest.CurrentVariant)"
        Write-Host "Diagnostics: $($session.Manifest.CurrentDiagnostics)"
        Write-Host "Archives: $(@($session.Manifest.ArchiveHistory).Count)"
    }

    $dlls = @()
    if (Test-Path -LiteralPath $Paths.F4SEPlugins -PathType Container) {
        $dlls = @(Get-ChildItem -LiteralPath $Paths.F4SEPlugins -File -Filter '*.dll' |
            Sort-Object Name)
    }
    if ($dlls.Count -eq 0) {
        Write-Host 'Active top-level F4SE DLLs: none'
    } else {
        Write-Host 'Active top-level F4SE DLLs:'
        foreach ($dll in $dlls) {
            Write-Host ('  {0}  SHA-256={1}' -f $dll.Name, (Get-Sha256 -LiteralPath $dll.FullName))
        }
    }

    $activePlugins = @(Get-ActivePluginNames -PluginsPath $Paths.PluginsTxt)
    if ($activePlugins.Count -eq 0) {
        Write-Host 'Active plugins.txt entries: none'
    } else {
        Write-Host ('Active plugins.txt entries: {0}' -f ($activePlugins -join ', '))
    }

    if (Test-Path -LiteralPath $Paths.FalloutCustom -PathType Leaf) {
        $loose = @(Select-String -LiteralPath $Paths.FalloutCustom `
            -Pattern '^\s*bInvalidateOlderFiles\s*=' -ErrorAction SilentlyContinue |
            ForEach-Object { $_.Line.Trim() })
        if ($loose.Count -gt 0) {
            Write-Host ('Loose-file setting: {0}' -f ($loose -join '; '))
        } else {
            Write-Host 'Loose-file setting: not explicitly set'
        }
    } else {
        Write-Host 'Loose-file setting: Fallout4Custom.ini missing'
    }

    if (Test-Path -LiteralPath $Paths.LoadingLog -PathType Leaf) {
        $log = Get-Item -LiteralPath $Paths.LoadingLog
        Write-Host ('LoadingScreens.log: {0} bytes, {1:o}' -f $log.Length, $log.LastWriteTimeUtc)
    } else {
        Write-Host 'LoadingScreens.log: missing'
    }
}

function Assert-BenchmarkSelfTest {
    param(
        [Parameter(Mandatory = $true)][bool]$Condition,
        [Parameter(Mandatory = $true)][string]$Message
    )
    if (-not $Condition) {
        throw "Benchmark harness self-test failed: $Message"
    }
}

function Assert-BenchmarkTextLine {
    param(
        [Parameter(Mandatory = $true)][string]$Text,
        [Parameter(Mandatory = $true)][string]$Expected
    )
    $lines = @($Text -split '\r?\n')
    Assert-BenchmarkSelfTest -Condition ($lines -contains $Expected) `
        -Message "generated configuration is missing '$Expected'"
}

function Invoke-SelfTest {
    $variant = 'gate-1cell'
    $profile = Get-VariantProfile -VariantName $variant

    Assert-BenchmarkSelfTest -Condition ([int]$profile.BenchmarkMode -eq 1) `
        -Message 'safe B profile must enable the combined DLL'
    Assert-BenchmarkSelfTest -Condition ([bool]$profile.MenuPreload) `
        -Message 'safe B profile must enable menu preload'
    Assert-BenchmarkSelfTest -Condition (-not [bool]$profile.NativeLinked) `
        -Message 'safe B profile must disable native linked/interior preload'
    Assert-BenchmarkSelfTest -Condition ([int]$profile.InteriorCellBuffer -eq 3) `
        -Message 'safe B profile must leave the vanilla interior buffer at 3'
    Assert-BenchmarkSelfTest -Condition ([bool]$profile.PreloadExteriorGates) `
        -Message 'safe B profile must enable exterior gates'
    Assert-BenchmarkSelfTest -Condition (-not [bool]$profile.HighFPSPhysicsFix) `
        -Message 'safe B profile must disable HFPF'
    Assert-BenchmarkSelfTest -Condition (-not [bool]$profile.Buffout4) `
        -Message 'normal safe B profile must disable Buffout'
    Assert-BenchmarkSelfTest -Condition (-not [bool]$profile.RequireDiagnostics) `
        -Message 'safe B profile must permit diagnostics-off timing'
    Assert-BenchmarkSelfTest `
        -Condition ($script:ControlledPresentInterval -eq 1) `
        -Message 'controlled present interval must be 1'
    Assert-BenchmarkSelfTest `
        -Condition ($script:ControlledBorderless -eq 1 -and
                    $script:ControlledFullScreen -eq 0 -and
                    $script:ControlledMaximizeWindow -eq 0) `
        -Message 'controlled display mode must be true borderless windowed'

    Assert-ProfileInvocation -VariantName $variant -Profile $profile `
        -DiagnosticsEnabled $false

    $mcm = New-UserMcmText -VariantName $variant -Profile $profile `
        -SessionPath '<self-test>' -DiagnosticsEnabled $false `
        -LoadingScreenModeValue 0
    $mcmDisplay = New-UserMcmText -VariantName $variant -Profile $profile `
        -SessionPath '<self-test>' -DiagnosticsEnabled $false `
        -LoadingScreenModeValue 3
    Assert-BenchmarkTextLine -Text $mcmDisplay -Expected 'iLoadingScreenMode=3'
    foreach ($line in @(
        'iLoadingScreenMode=0',
        'iBenchmarkMode=1',
        'bVanillaFades=1',
        'fMinSecondsForLoadFadeIn=1.5',
        'fLoadGameFadeSecs=1.0',
        'fFadeToBlackFadeSeconds=1.0',
        'fAutoDoorFadeSecs=0.5',
        'fNormalDoorFadeSecs=0.4',
        'fNormalDoorFadeWait=0.01',
        'bPreloadExteriorGates=1',
        'iExteriorGateDistanceCells=0',
        'bPreloadDiagnostics=0'
    )) {
        Assert-BenchmarkTextLine -Text $mcm -Expected $line
    }

    $custom = New-ControlledCustomIniText `
        -VariantName $variant -Profile $profile
    foreach ($line in @(
        'bUseMenuLoadCellPreload=1',
        'bPreloadLinkedAreas=0',
        'fTeleportPreloadDistance=2048.0000',
        'uGridsToLoad=5',
        'uInterior Cell Buffer=3',
        'bInvalidateOlderFiles=0'
    )) {
        Assert-BenchmarkTextLine -Text $custom -Expected $line
    }

    $fakePaths = [pscustomobject]@{
        InstalledDll = 'C:\self-test\LoadingScreens.dll'
        Buffout4Dll = 'C:\self-test\Buffout4.dll'
        HighFPSPhysicsFixDll = 'C:\self-test\HighFPSPhysicsFix.dll'
    }
    $allowed = @(Get-AllowedActiveF4SEDllPaths `
        -Paths $fakePaths -Profile $profile)
    Assert-BenchmarkSelfTest -Condition ($allowed.Count -eq 1) `
        -Message 'safe B profile must allow exactly one F4SE DLL'
    Assert-BenchmarkSelfTest `
        -Condition ($allowed[0] -eq $fakePaths.InstalledDll) `
        -Message 'the only allowed F4SE DLL must be LoadingScreens.dll'

    $buffoutProfile = Get-VariantProfile -VariantName 'gate-1cell-buffout'
    Assert-BenchmarkSelfTest -Condition ([bool]$buffoutProfile.Buffout4) `
        -Message 'Buffout safe B profile must enable Buffout'
    Assert-BenchmarkSelfTest -Condition (-not [bool]$buffoutProfile.HighFPSPhysicsFix) `
        -Message 'Buffout safe B profile must keep HFPF disabled'
    Assert-BenchmarkSelfTest -Condition (-not [bool]$buffoutProfile.NativeLinked) `
        -Message 'Buffout safe B profile must keep linked/interior preload disabled'
    Assert-BenchmarkSelfTest -Condition ([int]$buffoutProfile.ExteriorGateDistanceCells -eq 0) `
        -Message 'Buffout safe B profile must keep one-cell exterior gate distance'
    $buffoutAllowed = @(Get-AllowedActiveF4SEDllPaths `
        -Paths $fakePaths -Profile $buffoutProfile)
    Assert-BenchmarkSelfTest -Condition ($buffoutAllowed.Count -eq 2) `
        -Message 'Buffout safe B profile must allow exactly two F4SE DLLs'
    Assert-BenchmarkSelfTest `
        -Condition ($buffoutAllowed -contains $fakePaths.InstalledDll -and
                    $buffoutAllowed -contains $fakePaths.Buffout4Dll) `
        -Message 'Buffout safe B profile must allow only LoadingScreens and Buffout4'
    $buffoutConfig = New-ControlledBuffout4TomlText
    foreach ($line in @(
        'BGSAIWorldLocationRefRadiusNull = false',
        'FixScriptPageAllocation = false',
        'FixToggleScriptsCommand = false',
        'InteriorNavCut = false',
        'WorkBenchSwap = false',
        'MemoryManager = false',
        'ScaleformAllocator = false',
        'SmallBlockAllocator = false',
        'MaxPapyrusOpsPerFrame = 0'
    )) {
        Assert-BenchmarkTextLine -Text $buffoutConfig -Expected $line
    }

    $baselineBuffoutProfile = Get-VariantProfile `
        -VariantName 'baseline-buffout'
    Assert-BenchmarkSelfTest `
        -Condition ([int]$baselineBuffoutProfile.BenchmarkMode -eq 0) `
        -Message 'Buffout baseline must keep Faster Loadscreens passive'
    Assert-BenchmarkSelfTest `
        -Condition ([bool]$baselineBuffoutProfile.Buffout4) `
        -Message 'Buffout baseline must enable crash capture'
    Assert-BenchmarkSelfTest `
        -Condition (-not [bool]$baselineBuffoutProfile.NativeLinked -and
                    -not [bool]$baselineBuffoutProfile.PreloadExteriorGates -and
                    -not [bool]$baselineBuffoutProfile.HighFPSPhysicsFix) `
        -Message 'Buffout baseline must disable every preload/speed companion'

    $retiredRejected = $false
    try {
        [void](Get-VariantProfile -VariantName 'b-all-preload-buffer3')
    } catch {
        $retiredRejected = $true
    }
    Assert-BenchmarkSelfTest -Condition $retiredRejected `
        -Message 'unsafe historical B profile must remain retired'

    Write-Host 'Fallout4PreloadBenchmark gate-1cell safe-B self-test: PASS'
}

$resolvedGameRoot = [IO.Path]::GetFullPath($GameRoot)
$paths = Get-GamePaths -Root $resolvedGameRoot

switch ($Action) {
    'Status' {
        if ($Name) {
            throw 'Status does not accept a variant or run label.'
        }
        Invoke-Status -Paths $paths
    }
    'Stage' {
        if ([string]::IsNullOrWhiteSpace($Name)) {
            throw 'Stage requires a variant name.'
        }
        Invoke-Stage -VariantName $Name -Paths $paths -DiagnosticsEnabled $Diagnostics `
            -LoadingScreenModeValue $LoadingScreenMode
    }
    'Archive' {
        if ([string]::IsNullOrWhiteSpace($Name)) {
            throw 'Archive requires a run label.'
        }
        Invoke-Archive -RunLabel $Name -Paths $paths
    }
    'Restore' {
        if ($Name) {
            throw 'Restore does not accept a variant or run label.'
        }
        Invoke-Restore -Paths $paths
    }
    'SelfTest' {
        if ($Name) {
            throw 'SelfTest does not accept a variant or run label.'
        }
        Invoke-SelfTest
    }
}
